// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.15.6
// source: grpc/proto/bible.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Bible struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id   int32  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Text string `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
}

func (x *Bible) Reset() {
	*x = Bible{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_proto_bible_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Bible) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Bible) ProtoMessage() {}

func (x *Bible) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_proto_bible_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Bible.ProtoReflect.Descriptor instead.
func (*Bible) Descriptor() ([]byte, []int) {
	return file_grpc_proto_bible_proto_rawDescGZIP(), []int{0}
}

func (x *Bible) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Bible) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type Bibles struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Bible []*Bible `protobuf:"bytes,1,rep,name=bible,proto3" json:"bible,omitempty"`
}

func (x *Bibles) Reset() {
	*x = Bibles{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_proto_bible_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Bibles) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Bibles) ProtoMessage() {}

func (x *Bibles) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_proto_bible_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Bibles.ProtoReflect.Descriptor instead.
func (*Bibles) Descriptor() ([]byte, []int) {
	return file_grpc_proto_bible_proto_rawDescGZIP(), []int{1}
}

func (x *Bibles) GetBible() []*Bible {
	if x != nil {
		return x.Bible
	}
	return nil
}

var File_grpc_proto_bible_proto protoreflect.FileDescriptor

var file_grpc_proto_bible_proto_rawDesc = []byte{
	0x0a, 0x16, 0x67, 0x72, 0x70, 0x63, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x62, 0x69, 0x62,
	0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a,
	0x15, 0x67, 0x72, 0x70, 0x63, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x75, 0x74, 0x69, 0x6c,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x2b, 0x0a, 0x05, 0x42, 0x69, 0x62, 0x6c, 0x65, 0x12,
	0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x69, 0x64, 0x12,
	0x12, 0x0a, 0x04, 0x74, 0x65, 0x78, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74,
	0x65, 0x78, 0x74, 0x22, 0x2c, 0x0a, 0x06, 0x42, 0x69, 0x62, 0x6c, 0x65, 0x73, 0x12, 0x22, 0x0a,
	0x05, 0x62, 0x69, 0x62, 0x6c, 0x65, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x42, 0x69, 0x62, 0x6c, 0x65, 0x52, 0x05, 0x62, 0x69, 0x62, 0x6c,
	0x65, 0x32, 0x92, 0x01, 0x0a, 0x0c, 0x42, 0x69, 0x62, 0x6c, 0x65, 0x53, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x12, 0x28, 0x0a, 0x03, 0x47, 0x65, 0x74, 0x12, 0x11, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2e, 0x49, 0x6e, 0x74, 0x33, 0x32, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x1a, 0x0c, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x42, 0x69, 0x62, 0x6c, 0x65, 0x22, 0x00, 0x12, 0x25, 0x0a, 0x04,
	0x4c, 0x69, 0x73, 0x74, 0x12, 0x0c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x45, 0x6d, 0x70,
	0x74, 0x79, 0x1a, 0x0d, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x42, 0x69, 0x62, 0x6c, 0x65,
	0x73, 0x22, 0x00, 0x12, 0x31, 0x0a, 0x06, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x12, 0x12, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x56, 0x61, 0x6c, 0x75,
	0x65, 0x1a, 0x11, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x49, 0x6e, 0x74, 0x33, 0x32, 0x56,
	0x61, 0x6c, 0x75, 0x65, 0x22, 0x00, 0x42, 0x0a, 0x5a, 0x08, 0x2f, 0x67, 0x72, 0x70, 0x63, 0x2f,
	0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_grpc_proto_bible_proto_rawDescOnce sync.Once
	file_grpc_proto_bible_proto_rawDescData = file_grpc_proto_bible_proto_rawDesc
)

func file_grpc_proto_bible_proto_rawDescGZIP() []byte {
	file_grpc_proto_bible_proto_rawDescOnce.Do(func() {
		file_grpc_proto_bible_proto_rawDescData = protoimpl.X.CompressGZIP(file_grpc_proto_bible_proto_rawDescData)
	})
	return file_grpc_proto_bible_proto_rawDescData
}

var file_grpc_proto_bible_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_grpc_proto_bible_proto_goTypes = []interface{}{
	(*Bible)(nil),       // 0: proto.Bible
	(*Bibles)(nil),      // 1: proto.Bibles
	(*Int32Value)(nil),  // 2: proto.Int32Value
	(*Empty)(nil),       // 3: proto.Empty
	(*StringValue)(nil), // 4: proto.StringValue
}
var file_grpc_proto_bible_proto_depIdxs = []int32{
	0, // 0: proto.Bibles.bible:type_name -> proto.Bible
	2, // 1: proto.BibleService.Get:input_type -> proto.Int32Value
	3, // 2: proto.BibleService.List:input_type -> proto.Empty
	4, // 3: proto.BibleService.Create:input_type -> proto.StringValue
	0, // 4: proto.BibleService.Get:output_type -> proto.Bible
	1, // 5: proto.BibleService.List:output_type -> proto.Bibles
	2, // 6: proto.BibleService.Create:output_type -> proto.Int32Value
	4, // [4:7] is the sub-list for method output_type
	1, // [1:4] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_grpc_proto_bible_proto_init() }
func file_grpc_proto_bible_proto_init() {
	if File_grpc_proto_bible_proto != nil {
		return
	}
	file_grpc_proto_util_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_grpc_proto_bible_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Bible); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpc_proto_bible_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Bibles); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_grpc_proto_bible_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_grpc_proto_bible_proto_goTypes,
		DependencyIndexes: file_grpc_proto_bible_proto_depIdxs,
		MessageInfos:      file_grpc_proto_bible_proto_msgTypes,
	}.Build()
	File_grpc_proto_bible_proto = out.File
	file_grpc_proto_bible_proto_rawDesc = nil
	file_grpc_proto_bible_proto_goTypes = nil
	file_grpc_proto_bible_proto_depIdxs = nil
}
