version: "3"

services:
  master:
    build:
      target: prod
      context: ./
      dockerfile: Dockerfile
    image: ${DOCKER_IMAGE_PREFIX}/app:${DOCKER_APP_TAG}
    command: /root/app -rpc=true -rpc_port=8000 -http=false
    environment:
      MYSQL: ${MYSQL}
    depends_on:
      - mysql
    restart: always
  slave:
    image: ${DOCKER_IMAGE_PREFIX}/app:${DOCKER_APP_TAG}
    command: /root/app -master=nginx:8000
    environment:
      CSRF_TOKEN_SECRET: ${CSRF_TOKEN_SECRET}
      SESSION_NAME: ${SESSION_NAME}
      SESSION_SECRET: ${SESSION_SECRET}
    depends_on:
      - master
    restart: always
  nginx:
    build:
      target: nginx
      context: ./
      dockerfile: Dockerfile
    image: ${DOCKER_IMAGE_PREFIX}/nginx:${DOCKER_APP_TAG}
    ports:
      - "80:80"
    depends_on:
      - master
      - slave
    restart: always
  mysql:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${DOCKER_MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DOCKER_MYSQL_DATABASE}
      MYSQL_USER: ${DOCKER_MYSQL_USER}
      MYSQL_PASSWORD: ${DOCKER_MYSQL_PASSWORD}
    restart: always
  redis:
    image: redis:alpine
    restart: always
