version: "3"

services:
  master:
    build:
      target: prod
      context: ./
      dockerfile: Dockerfile
    command: /root/app -rpc=true -rpc_port=8000 -http=false
    container_name: master
    environment:
      MYSQL: ${MYSQL}
  slave_1:
    image: ${CUSTOMIZE_NETWORK_NAME}_master
    command: /root/app -master=master:8000
    container_name: slave_1
    depends_on:
      - master
    environment:
      CSRF_TOKEN_SECRET: ${CSRF_TOKEN_SECRET}
      SESSION_NAME: ${SESSION_NAME}
      SESSION_SECRET: ${SESSION_SECRET}
  slave_2:
    image: ${CUSTOMIZE_NETWORK_NAME}_master
    command: /root/app -master=master:8000
    container_name: slave_2
    depends_on:
      - master
    environment:
      CSRF_TOKEN_SECRET: ${CSRF_TOKEN_SECRET}
      SESSION_NAME: ${SESSION_NAME}
      SESSION_SECRET: ${SESSION_SECRET}
  nginx:
    build:
      target: nginx
      context: ./
      dockerfile: Dockerfile
    restart: always
    container_name: nginx
    ports:
    - "80:80"
#  mysql:
#    image: mysql
#    container_name: mysql
#    restart: always
#    environment:
#      MYSQL_ROOT_PASSWORD: woaiyao
#      MYSQL_DATABASE: wordpress
#      MYSQL_USER: wordpress
#      MYSQL_PASSWORD: wordpress

networks:
  default:
    external:
      name: ${CUSTOMIZE_NETWORK_NAME}