version: "3"

services:
  master:
    build:
      target: prod
      context: ./
      dockerfile: Dockerfile
    command: /root/app -rpc=true -rpc_port=8000 -http=false
    container_name: master
    environment:
      MYSQL: "root:woaiyao@tcp(mysql:3306)/mysite?charset=utf8mb4&parseTime=True&loc=Local"
  slave_1:
    build:
      target: prod
      context: ./
      dockerfile: Dockerfile
    command: /root/app -master=master:8000
    container_name: slave_1
  slave_2:
    build:
      target: prod
      context: ./
      dockerfile: Dockerfile
    command: /root/app -master=master:8000
    container_name: slave_2
  nginx:
    build:
      target: nginx
      context: ./
      dockerfile: Dockerfile
    restart: always
    container_name: nginx
    ports:
    - "80:80"
#  mysql:
#    image: mysql
#    container_name: mysql
#    restart: always
#    networks:
#      mysite:
#    environment:
#      MYSQL_ROOT_PASSWORD: wordpress
#      MYSQL_DATABASE: wordpress
#      MYSQL_USER: wordpress
#      MYSQL_PASSWORD: wordpress

networks:
  default:
    external:
      name: mysite